set -g @plugin 'catppuccin/tmux#v2.3.0'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tpm'

set -g mouse on
set -g set-clipboard on               # use system clipboard

# --- Catppuccin Plugin & Module Configurations ---
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_text "#W"
set -g @catppuccin_window_current_text "#W#{?window_zoomed_flag,(),}"
set -g @catppuccin_directory_text "#{b:pane_current_path}"

# --- Native Status Placement & Adjustments ---
set -g status-position top 
set -g renumber-windows on            # renumber windows as they are closed
set -g base-index 1                   # start windows index at 1 instead of 0
set -g status-left-length 100
set -g status-right-length 100
set -g status-left "#{E:@catppuccin_status_session}"
set -g status-right "#{E:@catppuccin_status_directory}#[fg=default,bg=default]"

# Use vi or emacs-style key bindings in copy and choice modes.
set -g mode-keys vi

# Match Vim's intuitive selection mapping behavior
bind-key -T copy-mode-vi 'v' send -X begin-selection     # Begin selection in copy mode.
bind-key -T copy-mode-vi 'C-v' send -X rectangle-toggle  # Begin selection in copy mode.
bind-key -T copy-mode-vi 'y' send -X copy-selection      # Yank selection in copy mode.

# Use current path
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
# more convenient...
bind | split-window -v -c "#{pane_current_path}"
bind \\ split-window -h -c "#{pane_current_path}"

# needs to be at the bottom
run '~/.tmux/plugins/tpm/tpm'
