#!/bin/sh

cd "$HOME"
echo "Init submodules"
yadm submodule update --recursive --init

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  # well 🥴... looks like a 🐓 and 🥚 problem here...
  # we likely already have brew installed because that is what
  # we likely used to install yadm to begin with...

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi

fi

# Setup nvm
command -v nvm >/dev/null 2>&1 || {
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash

  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
}

# Setup nodejs
command -v node >/dev/null 2>&1 || {
  # Install node 16
  echo "Node JS not found, installing..."
  nvm install 16
  nvm use 16
}

# Setup nodejs
command -v yarn >/dev/null 2>&1 || {
  # Install yarn
  echo "Yarn not found, installing..."
  npm install yarn -g
}

# Setup gotags (also required for SpaceVim's Golang layer)
go install github.com/jstemmer/gotags@latest

pip3 install --upgrade pip
python3 -m pip install --upgrade pynvim

# Setup SpaceVim
curl -sLf https://spacevim.org/install.sh | bash
