[options]
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"

    enable_guicolors = true

    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_statusline_mode = false

    enable_tabline_ft_icon = true
    enable_tabline_filetype_icon = true
    enable_vimfiler_filetypeicon = true

    autocomplete_method = "coc"
    snippet_engine = "ultisnips"

    bootstrap_before = 'ainacio#before'
    bootstrap_after = 'ainacio#after'

# Enable autocomplete layer
[[layers]]
    name = 'autocomplete'
    auto_completion_return_key_behavior = "complete"
    auto_completion_tab_key_behavior = "smart"

[[layers]]
    name = 'shell'
    default_position = 'top'
    default_height = 30

# TODO - check https://github.com/SpaceVim/SpaceVim/issues/1882
[[layers]]
    name = "fzf"

[[layers]]
  name = "lang#go"

[[layers]]
    name = 'lang#javascript'
    format_on_save = true

[[layers]]
  name = "lang#lua"

[[layers]]
  name = "lang#html"
  emmet_leader_key = "<C-e>"
  emmet_filetyps = ['html']

# Plugins
[[custom_plugins]]
    repo = "https://github.com/junegunn/fzf.vim"
    merged = false

[[custom_plugins]]
    repo = "https://github.com/junegunn/fzf"
    merged = false

[[custom_plugins]]
    repo = "https://github.com/junegunn/fzf"
    merged = false

[[custom_plugins]]
    repo = 'tpope/vim-unimpaired'
    meged = false

[[custom_plugins]]
    repo = 'tpope/vim-repeat'
    meged = false

# telescope requirements...
[[custom_plugins]]
    repo = 'nvim-lua/popup.nvim'
    meged = false

[[custom_plugins]]
    repo = 'nvim-lua/plenary.nvim'
    meged = false

[[custom_plugins]]
    repo = 'nvim-telescope/telescope.nvim'
    meged = false

[[custom_plugins]]
    repo = 'nvim-telescope/telescope-fzy-native.nvim'
    meged = false

[[custom_plugins]]
    repo = 'editorconfig/editorconfig-vim'
    merged = false
